#Transformaciones Homogéneas

Las translaformaciones homogéneas sirven entre otras cosas para representar el giro y la traslación realizados sobre un sistema de referencia.

Esta utilidad de las matrices homogéneas cobra aún más importancia cuando se componen las matrices homogenenas para describir diversos giros y traslaciones consecutivos sobre un sistema de referencia determinado. 

De esta manera, una transformación puede descomponerse en la aplicación consecutiva de transformaciones simples.

### Funciones

En la siguiente seccion se definen las librerias matemáticas requeridas para ser usadas en la representacion de las matrices de transformacion homogéneas.


In [2]:
from sympy import Matrix, Symbol, sin, cos, pi
import numpy as np


def Rotx_matrix(alpha=0):
    alpha = Symbol(alpha) if isinstance(alpha, str) else alpha
    matrix_Rotx_alpha = Matrix([
        [1, 0         , 0           ,0],
        [0, cos(alpha), -sin(alpha) ,0],
        [0, sin(alpha), cos(alpha)  ,0],
        [0, 0         , 0           ,1]
    ])

    return matrix_Rotx_alpha

def Roty_matrix(phi=0):
    phi = Symbol(phi) if isinstance(phi, str) else phi
    matrix_Rot_phi = Matrix([
        [cos(phi) , 0, sin(phi) ,0],
        [0        , 1, 0        ,0],
        [-sin(phi), 0, cos(phi) ,0],
        [0        , 0, 0        ,1]
    ])

    return matrix_Rot_phi

def Rotz_matrix(theta=0):
    theta = Symbol(theta) if isinstance(theta, str) else theta
    matrix_Rot_theta = Matrix([
        [cos(theta), -sin(theta) ,0 ,0],
        [sin(theta), cos(theta)  ,0 ,0],
        [0         , 0           ,1 ,0],
        [0         , 0           ,0 ,1]
    ])

    return matrix_Rot_theta

def Matrix_transformation(Matriz_1,Matriz_2,Matriz_3):
    Matriz_T = Matriz_1 * Matriz_2 * Matriz_3

    if isinstance(Rotx_matrix(),float):
      if isinstance(Roty_matrix(),float):
        if isinstance(Rotz_matrix(),float):
          np.array(Matriz_T).astype(np.float64)
     

    return Matriz_T

def Posicion(p_x=0,p_y=0,p_z=0):
  x = Symbol('p_x') if isinstance(p_x, str) else p_x
  y = Symbol('p_y') if isinstance(p_y, str) else p_y
  z = Symbol('p_z') if isinstance(p_z, str) else p_z
  Trasla = Matrix([
      [1,0,0,x],
      [0,1,0,y],
      [0,0,1,z],
      [0,0,0,1]
  ])
  return Trasla


### Si observamos solamente la rotación del sistema

In [3]:
Rotx_matrix('alpha')

Matrix([
[1,          0,           0, 0],
[0, cos(alpha), -sin(alpha), 0],
[0, sin(alpha),  cos(alpha), 0],
[0,          0,           0, 1]])

In [4]:
Roty_matrix('phi')

Matrix([
[ cos(phi), 0, sin(phi), 0],
[        0, 1,        0, 0],
[-sin(phi), 0, cos(phi), 0],
[        0, 0,        0, 1]])

In [5]:
Rotz_matrix('theta')

Matrix([
[cos(theta), -sin(theta), 0, 0],
[sin(theta),  cos(theta), 0, 0],
[         0,           0, 1, 0],
[         0,           0, 0, 1]])

In [6]:
R = Matrix_transformation(Rotz_matrix('theta'),Roty_matrix('phi'),Rotx_matrix('alpha'))
R

Matrix([
[cos(phi)*cos(theta), sin(alpha)*sin(phi)*cos(theta) - sin(theta)*cos(alpha),  sin(alpha)*sin(theta) + sin(phi)*cos(alpha)*cos(theta), 0],
[sin(theta)*cos(phi), sin(alpha)*sin(phi)*sin(theta) + cos(alpha)*cos(theta), -sin(alpha)*cos(theta) + sin(phi)*sin(theta)*cos(alpha), 0],
[          -sin(phi),                                    sin(alpha)*cos(phi),                                     cos(alpha)*cos(phi), 0],
[                  0,                                                      0,                                                       0, 1]])

###Ahora si definimos la posición

In [7]:
P = Posicion(Symbol('p_x'),Symbol('p_y'),Symbol('p_z'))
P

Matrix([
[1, 0, 0, p_x],
[0, 1, 0, p_y],
[0, 0, 1, p_z],
[0, 0, 0,   1]])

###La matriz de transformación homogénea queda de la siguiente forma

In [8]:
T = P*R
T

Matrix([
[cos(phi)*cos(theta), sin(alpha)*sin(phi)*cos(theta) - sin(theta)*cos(alpha),  sin(alpha)*sin(theta) + sin(phi)*cos(alpha)*cos(theta), p_x],
[sin(theta)*cos(phi), sin(alpha)*sin(phi)*sin(theta) + cos(alpha)*cos(theta), -sin(alpha)*cos(theta) + sin(phi)*sin(theta)*cos(alpha), p_y],
[          -sin(phi),                                    sin(alpha)*cos(phi),                                     cos(alpha)*cos(phi), p_z],
[                  0,                                                      0,                                                       0,   1]])

###Ejemplo

####Solamente rotación en el sistema de referencia



In [9]:
alpha = -23
phi   = 84
theta = 126
gg = Matrix_transformation(Rotz_matrix(theta),Roty_matrix(phi),Rotx_matrix(alpha))
gg

Matrix([
[cos(84)*cos(126), -sin(126)*cos(23) - sin(23)*sin(84)*cos(126), sin(84)*cos(23)*cos(126) - sin(23)*sin(126), 0],
[sin(126)*cos(84),  cos(23)*cos(126) - sin(23)*sin(84)*sin(126), sin(23)*cos(126) + sin(84)*sin(126)*cos(23), 0],
[        -sin(84),                             -sin(23)*cos(84),                             cos(23)*cos(84), 0],
[               0,                                            0,                                           0, 1]])

In [10]:
r = np.matrix(gg, dtype=float)
r

matrix([[-0.64193139,  0.7615161 , -0.08953944,  0.        ],
        [-0.22440151, -0.29824621, -0.9277355 ,  0.        ],
        [-0.73319032, -0.57544976,  0.36233897,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

####Solamente traslación en el sistema de referencia

In [11]:
r_x = 0.6
r_y = 2.1
r_z = 1.2

pp = Posicion(r_x,r_y,r_z)
pp

Matrix([
[1, 0, 0, 0.6],
[0, 1, 0, 2.1],
[0, 0, 1, 1.2],
[0, 0, 0,   1]])

In [12]:
p = np.matrix(pp, dtype=float)
p

matrix([[1. , 0. , 0. , 0.6],
        [0. , 1. , 0. , 2.1],
        [0. , 0. , 1. , 1.2],
        [0. , 0. , 0. , 1. ]])

####Rotación seguida de una traslación

In [18]:
phi = 84
r_x = 0.7
r_y = 1.4
r_z = 1.5

rottras = Posicion(r_x,r_y,r_z) * Matrix_transformation(1,Roty_matrix(phi),1)
rottras

Matrix([
[ cos(84), 0, sin(84), 0.7],
[       0, 1,       0, 1.4],
[-sin(84), 0, cos(84), 1.5],
[       0, 0,       0,   1]])

In [19]:
np.matrix(rottras, dtype=float)

matrix([[-0.6800235 ,  0.        ,  0.73319032,  0.7       ],
        [ 0.        ,  1.        ,  0.        ,  1.4       ],
        [-0.73319032,  0.        , -0.6800235 ,  1.5       ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

###Traslación seguida de una rotación

In [20]:
phi = 84
r_x = 0.7
r_y = 1.4
r_z = 1.5

trasrot = Matrix_transformation(1,Roty_matrix(phi),1) * Posicion(r_x,r_y,r_z) 
trasrot

Matrix([
[ cos(84), 0, sin(84), 0.7*cos(84) + 1.5*sin(84)],
[       0, 1,       0,                       1.4],
[-sin(84), 0, cos(84), 1.5*cos(84) - 0.7*sin(84)],
[       0, 0,       0,                         1]])

In [21]:
np.matrix(trasrot, dtype=float)

matrix([[-0.6800235 ,  0.        ,  0.73319032,  0.62376903],
        [ 0.        ,  1.        ,  0.        ,  1.4       ],
        [-0.73319032,  0.        , -0.6800235 , -1.53326847],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

####Rotación en X e Y, Traslacion y Rotación en Z

In [13]:
alpha = 64
phi   = 84
theta = 126
r_x = 0.7
r_y = 1.4
r_z = 1.5

Matrix_transformation(Rotz_matrix(theta),1,1) * Posicion(r_x,r_y,r_z) * Matrix_transformation(Rotx_matrix(alpha),Roty_matrix(phi),1)



Matrix([
[cos(84)*cos(126) - sin(64)*sin(84)*sin(126), -sin(126)*cos(64), sin(64)*sin(126)*cos(84) + sin(84)*cos(126), -1.4*sin(126) + 0.7*cos(126)],
[sin(126)*cos(84) + sin(64)*sin(84)*cos(126),  cos(64)*cos(126), sin(84)*sin(126) - sin(64)*cos(84)*cos(126),  0.7*sin(126) + 1.4*cos(126)],
[                           -sin(84)*cos(64),           sin(64),                             cos(64)*cos(84),                          1.5],
[                                          0,                 0,                                           0,                            1]])

In [14]:
np.matrix(Matrix_transformation(Rotz_matrix(theta),1,1) * Posicion(r_x,r_y,r_z) * Matrix_transformation(Rotx_matrix(alpha),Roty_matrix(phi),1), dtype=float)

matrix([[-0.86452809, -0.12930929,  0.4856648 ,  0.19880174],
        [ 0.41236694,  0.36990701,  0.83253968,  1.55257137],
        [-0.28730593,  0.92002604, -0.26647212,  1.5       ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])